"use client";

import { useMemo, useState, type CSSProperties } from "react";
import { GripVertical } from "lucide-react";
import { LocalDateTime } from "@/components/local-date-time";
import { createClient } from "@/lib/supabase/client";

type Category = { id: string; name: string; color: string; sort_order: number };
type Team = { id: string; team_number: number; name: string };
type Ranking = { id: string; team_id: string; category_id: string | null; rank: number | null; note: string; created_by: string; updated_by: string; updated_at: string };
type Change = { id: string; team_id: string; action: "baseline" | "created" | "updated" | "deleted"; before_state: Record<string, unknown> | null; after_state: Record<string, unknown> | null; created_at: string; teams?: { team_number: number; name: string } | null; profiles?: { display_name: string } | null };
type EditValues = { rank: string; categoryId: string; note: string };

export function PicklistBoard({ organizationId, eventId, userId, canEdit, categories: initialCategories, teams: initialTeams, rankings: initialRankings, changes }: { organizationId: string; eventId: string; userId: string; canEdit: boolean; categories: Category[]; teams: Team[]; rankings: Ranking[]; changes: Change[] }) {
  const [categories, setCategories] = useState(initialCategories);
  const [teams, setTeams] = useState(initialTeams);
  const [rankings, setRankings] = useState(initialRankings);
  const [newCategory, setNewCategory] = useState("");
  const [color, setColor] = useState("#64748b");
  const [notice, setNotice] = useState("");
  const [draggedTeam, setDraggedTeam] = useState<string | null>(null);
  const byTeam = useMemo(() => new Map(rankings.map((ranking) => [ranking.team_id, ranking])), [rankings]);
  const teamOrder = useMemo(() => [...teams].sort((a, b) => (byTeam.get(a.id)?.rank ?? Number.MAX_SAFE_INTEGER) - (byTeam.get(b.id)?.rank ?? Number.MAX_SAFE_INTEGER) || a.team_number - b.team_number), [teams, byTeam]);

  async function createCategory() { const name = newCategory.trim(); if (!name || !canEdit) return; const supabase: any = createClient(); const { data, error } = await supabase.from("picklist_categories").insert({ organization_id: organizationId, name, color, sort_order: categories.length, created_by: userId }).select("id,name,color,sort_order").single(); if (error) return setNotice("Could not add that category. It may already exist."); setCategories((current) => [...current, data]); setNewCategory(""); }
  async function moveCategory(id: string, by: number) { if (!canEdit) return; const currentIndex = categories.findIndex((category) => category.id === id); const nextIndex = currentIndex + by; if (nextIndex < 0 || nextIndex >= categories.length) return; const next = [...categories]; [next[currentIndex], next[nextIndex]] = [next[nextIndex], next[currentIndex]]; const ordered = next.map((category, index) => ({ ...category, sort_order: index })); setCategories(ordered); const supabase: any = createClient(); await Promise.all(ordered.map((category) => supabase.from("picklist_categories").update({ sort_order: category.sort_order }).eq("id", category.id))); }
  async function save(teamId: string, values: EditValues) { if (!canEdit) return; const existing = byTeam.get(teamId); const supabase: any = createClient(); const { data, error } = await supabase.from("picklist_rankings").upsert({ organization_id: organizationId, event_id: eventId, team_id: teamId, created_by: existing?.created_by ?? userId, updated_by: userId, rank: values.rank ? Number(values.rank) : null, category_id: values.categoryId || null, note: values.note.trim() }, { onConflict: "event_id,team_id" }).select("id,team_id,category_id,rank,note,created_by,updated_by,updated_at").single(); if (error) return setNotice("Could not save that team. Try again."); setRankings((current) => [...current.filter((ranking) => ranking.id !== data.id), data]); setNotice(`Shared picklist updated for Team ${teams.find((team) => team.id === teamId)?.team_number}.`); }
  async function persistTeamOrder(next: Team[]) { const supabase: any = createClient(); const nextRankings = await Promise.all(next.map(async (team, index) => { const existing = byTeam.get(team.id); const { data } = await supabase.from("picklist_rankings").upsert({ organization_id: organizationId, event_id: eventId, team_id: team.id, created_by: existing?.created_by ?? userId, updated_by: userId, rank: index + 1, category_id: existing?.category_id ?? null, note: existing?.note ?? "" }, { onConflict: "event_id,team_id" }).select("id,team_id,category_id,rank,note,created_by,updated_by,updated_at").single(); return data; })); setRankings(nextRankings.filter(Boolean)); setTeams(next); setNotice("Shared team order saved."); }
  async function moveTeam(teamId: string, by: number) { if (!canEdit) return; const currentIndex = teamOrder.findIndex((team) => team.id === teamId); const nextIndex = currentIndex + by; if (nextIndex < 0 || nextIndex >= teamOrder.length) return; const next = [...teamOrder]; [next[currentIndex], next[nextIndex]] = [next[nextIndex], next[currentIndex]]; await persistTeamOrder(next); }
  async function dropTeam(targetId: string) { const sourceId = draggedTeam; setDraggedTeam(null); if (!sourceId || sourceId === targetId || !canEdit) return; const next = [...teamOrder]; const sourceIndex = next.findIndex((team) => team.id === sourceId); const targetIndex = next.findIndex((team) => team.id === targetId); const [source] = next.splice(sourceIndex, 1); next.splice(targetIndex, 0, source); await persistTeamOrder(next); }

  return <><section className="card"><div className="card-head"><div><h2>Shared strategy categories</h2><p className="muted">These categories and their order apply to everyone at this event.</p></div>{!canEdit && <span className="tag pending">View only</span>}</div><div className="category-list">{categories.map((category, index) => <span className="category-chip category-order" style={{ "--category": category.color } as CSSProperties} key={category.id}>{canEdit && <span className="category-order-buttons"><button type="button" aria-label={`Move ${category.name} earlier`} disabled={index === 0} onClick={() => moveCategory(category.id, -1)}>↑</button><button type="button" aria-label={`Move ${category.name} later`} disabled={index === categories.length - 1} onClick={() => moveCategory(category.id, 1)}>↓</button></span>}{category.name}</span>)}</div>{canEdit && <div className="category-create"><input aria-label="New category" value={newCategory} onChange={(event) => setNewCategory(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); createCategory(); } }} placeholder="Add a category" maxLength={48}/><input aria-label="Category color" type="color" value={color} onChange={(event) => setColor(event.target.value)}/><button className="button secondary" type="button" onClick={createCategory}>Add category</button></div>}</section><section className="card section"><div className="card-head"><div><h2>Event picklist</h2><p className="muted">One shared order for the strategy group. Drag on desktop, or use move controls on a phone.</p></div><span className="muted">{teams.length} teams</span></div><div className="picklist-grid">{teamOrder.map((team, index) => <PickRow key={team.id} team={team} categories={categories} canEdit={canEdit} initial={byTeam.get(team.id)} dragging={draggedTeam === team.id} canMoveUp={index > 0} canMoveDown={index < teamOrder.length - 1} onMoveUp={() => moveTeam(team.id, -1)} onMoveDown={() => moveTeam(team.id, 1)} onDragStart={() => setDraggedTeam(team.id)} onDrop={() => dropTeam(team.id)} onSave={save}/>)}</div>{notice && <p className="trend" aria-live="polite">{notice}</p>}</section><section className="card section"><div className="card-head"><div><h2>Picklist activity</h2><p className="muted">The latest shared changes, including who made them.</p></div><span className="muted">{changes.length} recent changes</span></div><div className="picklist-activity">{changes.length ? changes.map((change) => <ChangeRow key={change.id} change={change} categories={categories}/>) : <p className="muted">No shared edits have been recorded yet.</p>}</div></section></>;
}

function PickRow({ team, categories, initial, canEdit, dragging, canMoveUp, canMoveDown, onMoveUp, onMoveDown, onDragStart, onDrop, onSave }: { team: Team; categories: Category[]; initial?: Ranking; canEdit: boolean; dragging: boolean; canMoveUp: boolean; canMoveDown: boolean; onMoveUp: () => void; onMoveDown: () => void; onDragStart: () => void; onDrop: () => void; onSave: (teamId: string, values: EditValues) => Promise<void> }) {
  const [rank, setRank] = useState(initial?.rank?.toString() ?? "");
  const [categoryId, setCategoryId] = useState(initial?.category_id ?? "");
  const [note, setNote] = useState(initial?.note ?? "");
  const [saving, setSaving] = useState(false);
  return <article className={`pick-row ${canEdit ? "pick-row-editable" : ""} ${dragging ? "dragging" : ""}`} draggable={canEdit} onDragStart={canEdit ? onDragStart : undefined} onDragOver={canEdit ? (event) => event.preventDefault() : undefined} onDrop={canEdit ? onDrop : undefined}><div className="pick-team">{canEdit && <GripVertical aria-hidden="true" size={18}/>}<span><strong>{team.team_number}</strong><small>{team.name}</small></span></div>{canEdit ? <><div className="pick-mobile-order"><button type="button" disabled={!canMoveUp} onClick={onMoveUp}>Move up</button><button type="button" disabled={!canMoveDown} onClick={onMoveDown}>Move down</button></div><label>Rank<input value={rank} inputMode="numeric" pattern="[0-9]*" type="text" onChange={(event) => { const next = event.currentTarget.value; if (/^\d*$/.test(next)) setRank(next); }}/></label><label>Category<select value={categoryId} onChange={(event) => setCategoryId(event.target.value)}><option value="">Uncategorized</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="pick-note">Note<textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Why this team?" maxLength={2000}/></label><button className="button secondary" type="button" disabled={saving} onClick={async () => { setSaving(true); await onSave(team.id, { rank, categoryId, note }); setSaving(false); }}>{saving ? "Saving…" : "Save"}</button></> : <><div className="consensus-rank"><span>Rank</span><strong>{initial?.rank ?? "—"}</strong></div><div className="consensus-rank"><span>Category</span><strong>{categories.find((category) => category.id === initial?.category_id)?.name ?? "—"}</strong></div><div className="consensus-rank"><span>Note</span><strong>{initial?.note || "—"}</strong></div></>}</article>;
}

function ChangeRow({ change, categories }: { change: Change; categories: Category[] }) {
  const before = change.before_state ?? {};
  const after = change.after_state ?? {};
  const category = (id: unknown) => typeof id === "string" ? categories.find((item) => item.id === id)?.name ?? "Uncategorized" : "Uncategorized";
  const details = change.action === "baseline" ? "Adopted as the initial shared ranking" : change.action === "created" ? `Added at rank ${after.rank ?? "—"}` : [before.rank !== after.rank && `Rank ${before.rank ?? "—"} → ${after.rank ?? "—"}`, before.category_id !== after.category_id && `Category ${category(before.category_id)} → ${category(after.category_id)}`, before.note !== after.note && "Updated note"].filter(Boolean).join(" · ") || "Updated shared ranking";
  return <div className="picklist-activity-row"><div><strong>{change.teams ? `${change.teams.team_number} · ${change.teams.name}` : "Team"}</strong><span>{details}</span></div><small>{change.profiles?.display_name ?? "Unknown member"} · <LocalDateTime value={change.created_at}/></small></div>;
}
