"use client";

import { useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Category = { id: string; name: string; color: string; sort_order: number };
type Team = { id: string; team_number: number; name: string };
type Ranking = { id: string; team_id: string; category_id: string | null; rank: number | null; note: string; user_id: string };
export function PicklistBoard({ organizationId, eventId, userId, categories: initialCategories, teams, rankings: initialRankings }: { organizationId: string; eventId: string; userId: string; categories: Category[]; teams: Team[]; rankings: Ranking[] }) {
  const [categories, setCategories] = useState(initialCategories);
  const [rankings, setRankings] = useState(initialRankings.filter((ranking) => ranking.user_id === userId));
  const [newCategory, setNewCategory] = useState("");
  const [color, setColor] = useState("#64748b");
  const [notice, setNotice] = useState("");
  const rankingByTeam = useMemo(() => new Map(rankings.map((ranking) => [ranking.team_id, ranking])), [rankings]);
  async function createCategory() { const name = newCategory.trim(); if (!name) return; setNotice(""); const supabase: any = createClient(); const { data, error } = await supabase.from("picklist_categories").insert({ organization_id: organizationId, name, color, sort_order: categories.length, created_by: userId }).select("id,name,color,sort_order").single(); if (error) { setNotice("Could not add that category. It may already exist."); return; } setCategories((current) => [...current, data]); setNewCategory(""); setNotice("Category added."); }
  async function save(teamId: string, values: { rank: string; categoryId: string; note: string }) { setNotice(""); const supabase: any = createClient(); const { data, error } = await supabase.from("picklist_rankings").upsert({ organization_id: organizationId, event_id: eventId, team_id: teamId, user_id: userId, rank: values.rank ? Number(values.rank) : null, category_id: values.categoryId || null, note: values.note.trim() }, { onConflict: "event_id,team_id,user_id" }).select("id,team_id,category_id,rank,note,user_id").single(); if (error) { setNotice("Could not save this team. Try again."); return; } setRankings((current) => [...current.filter((ranking) => ranking.team_id !== teamId), data]); setNotice(`Team ${teams.find((team) => team.id === teamId)?.team_number} saved.`); }
  return <><section className="card"><div className="card-head"><div><h2>Your categories</h2><p className="muted">Define the labels your picklist uses—Elite, Nice, Good, Do not pick, or anything your strategy group needs.</p></div></div><div className="category-list">{categories.map((category) => <span className="category-chip" style={{"--category": category.color} as React.CSSProperties} key={category.id}>{category.name}</span>)}</div><div className="category-create"><input aria-label="New category" value={newCategory} onChange={(event) => setNewCategory(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); createCategory(); } }} placeholder="Add a category" maxLength={48}/><input aria-label="Category color" type="color" value={color} onChange={(event) => setColor(event.target.value)}/><button className="button secondary" type="button" onClick={createCategory}>Add category</button></div></section><section className="card section"><div className="card-head"><div><h2>Personal team board</h2><p className="muted">Ranks and notes are yours to edit; strategy members can see the shared board.</p></div><span className="muted">{teams.length} teams</span></div><div className="picklist-grid">{teams.map((team) => <PickRow key={team.id} team={team} categories={categories} initial={rankingByTeam.get(team.id)} onSave={save}/>)}</div>{notice && <p className="trend" aria-live="polite">{notice}</p>}</section></>;
}
function PickRow({ team, categories, initial, onSave }: { team: Team; categories: Category[]; initial?: Ranking; onSave: (teamId: string, values: { rank: string; categoryId: string; note: string }) => Promise<void> }) { const [rank, setRank] = useState(initial?.rank?.toString() ?? ""); const [categoryId, setCategoryId] = useState(initial?.category_id ?? ""); const [note, setNote] = useState(initial?.note ?? ""); const [saving, setSaving] = useState(false); return <article className="pick-row"><div><strong>{team.team_number}</strong><span>{team.name}</span></div><label>Rank<input value={rank} inputMode="numeric" type="number" min="1" onChange={(event) => setRank(event.target.value)}/></label><label>Category<select value={categoryId} onChange={(event) => setCategoryId(event.target.value)}><option value="">Uncategorized</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="pick-note">Note<textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Why this team?" maxLength={2000}/></label><button className="button secondary" type="button" disabled={saving} onClick={async () => { setSaving(true); await onSave(team.id, { rank, categoryId, note }); setSaving(false); }}>{saving ? "Saving…" : "Save"}</button></article>; }
