"use client";
import { useActionState } from "react";
import { createEvent, importTbaEvent, inviteMember, publishFormDefinition, type ActionState } from "@/lib/admin-actions";
import { DEFAULT_2026_FORM } from "@wildcard/shared";
const initial:ActionState={};
function Message({state}:{state:ActionState}){return state.error?<p className="error">{state.error}</p>:state.success?<p className="trend">{state.success}</p>:null}
export function EventCreateForm(){const[state,action,pending]=useActionState(createEvent,initial);return <form action={action} className="card" style={{marginBottom:18}}><h2>Create an event</h2><div className="form-grid section"><div className="field"><label>Event name</label><input name="name" required placeholder="Hudson Valley Regional"/></div><div className="field"><label>TBA event key</label><input name="eventKey" required placeholder="2026nyhv"/></div></div><div style={{marginTop:13}}><button className="button" disabled={pending}>{pending?"Creating…":"Create event"}</button></div><Message state={state}/></form>}
export function FormPublisher(){const[state,action,pending]=useActionState(publishFormDefinition,initial);return <form action={action}><div className="field"><label>Form schema JSON</label><textarea name="schema" defaultValue={JSON.stringify(DEFAULT_2026_FORM,null,2)} style={{minHeight:280,fontFamily:"'DM Mono', monospace",fontSize:11}}/></div><div style={{marginTop:13}}><button className="button" disabled={pending}>{pending?"Publishing…":"Publish new version"}</button></div><Message state={state}/></form>}
export function InviteMemberForm(){const[state,action,pending]=useActionState(inviteMember,initial);return <form action={action} className="card" style={{marginTop:18}}><h2>Invite a teammate</h2><div className="form-grid section"><div className="field"><label>Email</label><input name="email" type="email" required placeholder="scout@example.com"/></div><div className="field"><label>Role</label><select name="role" defaultValue="scout"><option value="scout">Scout</option><option value="strategist">Strategist</option><option value="admin">Admin</option><option value="developer">Developer</option></select></div></div><div style={{marginTop:13}}><button className="button" disabled={pending}>{pending?"Sending…":"Send invitation"}</button></div><Message state={state}/></form>}
export function TbaImportForm(){const[state,action,pending]=useActionState(importTbaEvent,initial);return <form action={action}><div className="field"><label>TBA event key</label><input name="eventKey" required placeholder="2026nyhv"/></div><div style={{marginTop:13}}><button className="button" disabled={pending}>{pending?"Importing…":"Import event, teams & schedule"}</button></div><Message state={state}/></form>}
