"use client";
import { useActionState } from "react";
import { createEvent, deleteEvent, generateObjectiveAssignments, importTbaEvent, inviteMember, publishFormDefinition, setActiveEvent, setMemberRole, setObjectiveAssignment, type ActionState } from "@/lib/admin-actions";
import { DEFAULT_2026_FORM } from "@wildcard/shared";
const initial:ActionState={};
function Message({state}:{state:ActionState}){return state.error?<p className="error">{state.error}</p>:state.success?<p className="trend">{state.success}</p>:null}
export function EventCreateForm(){const[state,action,pending]=useActionState(createEvent,initial);return <form action={action} className="card" style={{marginBottom:18}}><h2>Create an empty event</h2><p className="muted" style={{lineHeight:1.6,marginBottom:0}}>Use this only when an event is not on TBA. It does not import teams or a schedule.</p><div className="form-grid section"><div className="field"><label>Event name</label><input name="name" required placeholder="Hudson Valley Regional"/></div><div className="field"><label>TBA-style event key</label><input name="eventKey" required placeholder="2026nyhv"/></div></div><div style={{marginTop:13}}><button className="button secondary" disabled={pending}>{pending?"Creating…":"Create empty event"}</button></div><Message state={state}/></form>}
export function FormPublisher(){const[state,action,pending]=useActionState(publishFormDefinition,initial);return <form action={action}><div className="field"><label>Form schema JSON</label><textarea name="schema" defaultValue={JSON.stringify(DEFAULT_2026_FORM,null,2)} style={{minHeight:280,fontFamily:"'DM Mono', monospace",fontSize:11}}/></div><div style={{marginTop:13}}><button className="button" disabled={pending}>{pending?"Publishing…":"Publish new version"}</button></div><Message state={state}/></form>}
export function InviteMemberForm(){const[state,action,pending]=useActionState(inviteMember,initial);return <form action={action} className="card" style={{marginTop:18}}><h2>Invite a teammate</h2><div className="form-grid section"><div className="field"><label>Email</label><input name="email" type="email" required placeholder="scout@example.com"/></div><div className="field"><label>Role</label><select name="role" defaultValue="scout"><option value="scout">Scout</option><option value="strategist">Strategist</option><option value="admin">Admin</option><option value="developer">Developer</option></select></div></div><div style={{marginTop:13}}><button className="button" disabled={pending}>{pending?"Sending…":"Send invitation"}</button></div><Message state={state}/></form>}
export function MemberRoleEditor({userId,role}:{userId:string;role:string}){const[state,action,pending]=useActionState(setMemberRole,initial);return <form action={action} style={{display:"flex",alignItems:"center",gap:8,flexWrap:"wrap"}}><input type="hidden" name="userId" value={userId}/><select name="role" defaultValue={role} disabled={pending}><option value="scout">Scout</option><option value="strategist">Strategist</option><option value="master">Master</option><option value="admin">Admin</option><option value="developer">Developer</option></select><button className="button secondary" disabled={pending}>{pending?"Saving…":"Save role"}</button><Message state={state}/></form>}
export function TbaImportForm(){const[state,action,pending]=useActionState(importTbaEvent,initial);return <form action={action}><div className="field"><label>TBA event key</label><input name="eventKey" required placeholder="2026nyhv" autoCapitalize="none" spellCheck={false}/><p className="muted" style={{lineHeight:1.6,margin:"7px 0 0"}}>On The Blue Alliance, open the event and copy the part after <code>/event/</code> in its URL. Example: <code>thebluealliance.com/event/2026nyhv</code> → <code>2026nyhv</code>.</p></div><div style={{marginTop:13}}><button className="button" disabled={pending}>{pending?"Importing…":"Import from TBA"}</button></div><Message state={state}/></form>}
export function GenerateAssignmentsForm({eventId}:{eventId:string}){const[state,action,pending]=useActionState(generateObjectiveAssignments,initial);return <form action={action}><input type="hidden" name="eventId" value={eventId}/><button className="button" disabled={pending}>{pending?"Creating…":"Create scout assignments"}</button><p className="muted" style={{lineHeight:1.6,margin:"8px 0 0"}}>Creates one objective assignment for every team appearance, rotating through Scout-role users and keeping existing assignments.</p><Message state={state}/></form>}
export function AssignmentEditor({matchId,teamId,teamLabel,scoutUserIds=[],scouts}:{matchId:string;teamId:string;teamLabel:string;scoutUserIds?:string[];scouts:{id:string;name:string}[]}){const[state,action,pending]=useActionState(setObjectiveAssignment,initial);const assigned=scouts.filter(s=>scoutUserIds.includes(s.id));return <form action={action} className="assignment-editor"><input type="hidden" name="matchId" value={matchId}/><input type="hidden" name="teamId" value={teamId}/><strong>{teamLabel}</strong>{assigned.length>0&&<span className="muted">Assigned: {assigned.map(s=>s.name).join(", ")}</span>}<select name="scoutUserId" defaultValue="" disabled={pending}><option value="">Clear all assignments</option>{scouts.filter(s=>!scoutUserIds.includes(s.id)).map(scout=><option key={scout.id} value={scout.id}>Add {scout.name}</option>)}</select><button className="button secondary" disabled={pending}>{pending?"Saving…":"Update"}</button><Message state={state}/></form>}
export function SetActiveEventForm({eventId,active}:{eventId:string;active:boolean}){const[state,action,pending]=useActionState(setActiveEvent,initial);return <form action={action}><input type="hidden" name="eventId" value={eventId}/><button className="button secondary" disabled={pending||active}>{active?"Active":pending?"Activating…":"Set active"}</button><Message state={state}/></form>}
export function DeleteEventForm({eventId,eventName}:{eventId:string;eventName:string}){const[state,action,pending]=useActionState(deleteEvent,initial);return <form action={action} onSubmit={event=>{if(!window.confirm(`Delete ${eventName}? Its schedule and assignments will also be removed. Events with submissions are protected.`))event.preventDefault();}}><input type="hidden" name="eventId" value={eventId}/><input type="hidden" name="eventName" value={eventName}/><button className="button danger" disabled={pending}>{pending?"Deleting…":"Delete"}</button><Message state={state}/></form>}
