import { AppShell, PageHeader } from "@/components/app-shell";
import { createClient } from "@/lib/supabase/server";
import { notFound } from "next/navigation";
import Link from "next/link";
import { LiveRefresh } from "@/components/live-refresh";

export default async function TeamDetail({ params }: { params: Promise<{ eventId: string; teamNumber: string }> }) {
  const { eventId: eventKey, teamNumber } = await params; const number = Number(teamNumber);
  if (!Number.isSafeInteger(number) || number < 1) notFound();
  const supabase = await createClient();
  const {data:event}=await supabase.from("events").select("id,event_key,name").eq("event_key",eventKey).maybeSingle(); if(!event)notFound();
  const { data: eventTeam } = await supabase.from("event_teams").select("teams(id,team_number,name)").eq("event_id", event.id).eq("teams.team_number", number).maybeSingle();
  const team = eventTeam?.teams as unknown as { id: string; team_number: number; name: string } | null;
  if (!team) notFound();
  const [{data:submissions},{data:entries},{data:notes}]=await Promise.all([supabase.from("match_submissions").select("id,status,submitted_at,matches(match_number)").eq("team_id",team.id).eq("event_id",event.id).order("submitted_at",{ascending:false}).limit(20),(supabase as any).from("scouting_entries").select("entry_type,payload,submitted_at").eq("team_id",team.id).eq("event_id",event.id).order("submitted_at",{ascending:false}),(supabase as any).from("team_notes").select("note,created_at,profiles(display_name)").eq("team_id",team.id).eq("event_id",event.id).order("created_at",{ascending:false})]);
  const {data:photos}=await (supabase as any).from("pit_photos").select("id,storage_path").eq("team_id",team.id).eq("event_id",event.id).order("created_at",{ascending:false});
  const photoUrls=(await Promise.all((photos??[]).map(async(photo:any)=>{const{data}=await supabase.storage.from("pit-photos").createSignedUrl(photo.storage_path,3600);return data?.signedUrl;}))).filter(Boolean) as string[];
  const matchEntries=(entries??[]).filter((entry:any)=>entry.entry_type==='match'); const pit=(entries??[]).find((entry:any)=>entry.entry_type==='pit'); const averageFuel=matchEntries.length?Math.round(matchEntries.reduce((sum:number,entry:any)=>sum+Number(entry.payload?.auto_fuel??0)+Number(entry.payload?.teleop_fuel??0),0)/matchEntries.length):0;
  return <AppShell active="Teams"><LiveRefresh tables={["match_submissions","scouting_entries","team_notes","pit_photos"]}/><PageHeader eyebrow={event.name} title={`${team.team_number} · ${team.name}`}/><div className="grid stats"><div className="card"><div className="stat-label">Match entries</div><div className="stat-value">{matchEntries.length+ (submissions?.length??0)}</div></div><div className="card"><div className="stat-label">Average fuel</div><div className="stat-value">{averageFuel}</div></div><div className="card"><div className="stat-label">Pit scouting</div><div className="stat-value" style={{fontSize:22}}>{pit?'Complete':'Pending'}</div></div><div className="card"><div className="stat-label">External data</div><Link className="link" href={`https://www.thebluealliance.com/team/${team.team_number}`} target="_blank">Open TBA →</Link></div></div>{photoUrls.length>0&&<section className="card section"><h2>Pit photos</h2><div className="pit-photo-grid">{photoUrls.map((url,index)=><img key={url} src={url} alt={`${team.team_number} pit photo ${index+1}`}/>)}</div></section>}<div className="page-grid section"><section className="card"><div className="card-head"><h2>Match history</h2><span className="muted">Live updates enabled</span></div>{submissions?.length ? submissions.map((submission:any)=><div className="list-row" key={submission.id}><div><strong>Qualification {submission.matches?.match_number}</strong><div className="muted">{submission.submitted_at?new Date(submission.submitted_at).toLocaleString():'Draft'}</div></div><span className={`tag ${submission.status==='submitted'?'complete':'pending'}`}>{submission.status}</span></div>):<p className="muted">No match entries yet.</p>}</section><aside className="card"><h2>Global scout notes</h2>{notes?.length?notes.map((note:any,index:number)=><p key={index} className="muted">{note.note}</p>):<p className="muted">No shared notes yet.</p>}<Link className="link" href={`/scout/manual`}>Add pit or pre-scout data →</Link></aside></div></AppShell>;
}
