"use client";

import Link from "next/link";
import { ResponsiveContainer, Line, LineChart, CartesianGrid, Tooltip, XAxis, YAxis } from "recharts";
import { useState } from "react";

type MetricKey = "totalFuel" | "autoFuel" | "teleopFuel" | "fouls" | "defense" | "broken";
const metricOptions: { key: MetricKey; label: string; color: string }[] = [{ key: "totalFuel", label: "Avg fuel", color: "#f24444" }, { key: "autoFuel", label: "Auto fuel", color: "#f2bf44" }, { key: "teleopFuel", label: "Teleop fuel", color: "#60a5fa" }, { key: "fouls", label: "Fouls", color: "#c084fc" }, { key: "defense", label: "Defense", color: "#34d399" }, { key: "broken", label: "Broken", color: "#fb7185" }];
export type TimelineMatch = { id: string; label: string; alliance: "red" | "blue"; outcome: "win" | "loss" | "tie" | "pending"; score: string; tbaUrl?: string; reportUrl?: string; hasScout: boolean; totalFuel: number | null; autoFuel: number | null; teleopFuel: number | null; fouls: number | null; defense: number | null; broken: number | null };
const label = (outcome: TimelineMatch["outcome"]) => outcome === "win" ? "Won" : outcome === "loss" ? "Lost" : outcome === "tie" ? "Tied" : "Pending";
const value = (number: number | null) => number === null ? "—" : number.toFixed(2);

export function TeamMatchTimeline({ matches }: { matches: TimelineMatch[] }) {
  const [metrics, setMetrics] = useState<MetricKey[]>(["totalFuel", "autoFuel", "teleopFuel"]);
  const hasData = matches.some((match) => match.hasScout);
  const chartData = matches.map((match) => ({ ...match, match: match.label, ...Object.fromEntries(metricOptions.map(({ key }) => [key, match[key] ?? undefined])) }));
  const toggleMetric = (key: MetricKey) => setMetrics((current) => current.includes(key) ? current.length === 1 ? current : current.filter((item) => item !== key) : [...current, key].slice(-4));
  return <section className="card team-timeline-card"><div className="card-head"><div><h2>Match timeline</h2><p className="muted">Results, alliance, and scouting coverage in one view.</p></div><span className="muted">{matches.filter((match) => match.hasScout).length} / {matches.length} scouted</span></div>{matches.length ? <>{hasData ? <><div className="team-timeline-metrics" role="group" aria-label="Chart metrics">{metricOptions.map((metric) => <button type="button" key={metric.key} className={metrics.includes(metric.key) ? "active" : ""} onClick={() => toggleMetric(metric.key)}>{metric.label}</button>)}</div><div className="team-timeline-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={chartData} margin={{ top: 8, right: 8, bottom: 0, left: -16 }}><CartesianGrid stroke="#303640" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="match" tick={{ fill: "#969dab", fontSize: 10 }} tickLine={false} axisLine={false}/><YAxis tick={{ fill: "#969dab", fontSize: 10 }} tickLine={false} axisLine={false} width={32}/><Tooltip contentStyle={{ background: "#15181d", border: "1px solid #303640", borderRadius: 8, fontSize: 12 }} labelStyle={{ color: "#f3f4f6", fontWeight: 700 }} formatter={(item) => typeof item === "number" ? item.toFixed(2) : item ?? "—"}/>{metricOptions.filter((metric) => metrics.includes(metric.key)).map((metric) => <Line key={metric.key} type="monotone" dataKey={metric.key} name={metric.label} stroke={metric.color} strokeWidth={metric.key === "totalFuel" ? 3 : 2} connectNulls={false} dot={{ r: 3, fill: metric.color, strokeWidth: 0 }}/>)}</LineChart></ResponsiveContainer></div></> : <p className="muted team-timeline-empty">No submitted match reports yet. Official results will still appear below.</p>}<div className="team-timeline-list">{matches.map((match) => <article key={match.id} className={`team-timeline-row ${match.alliance} ${match.hasScout ? "scouted" : "missing"}`}><div className="team-timeline-match"><strong>{match.label}</strong><span className={match.alliance}>{match.alliance}</span></div><div className="team-timeline-result"><strong>{label(match.outcome)}</strong><span>{match.score}</span></div><div className="team-timeline-coverage"><strong>{match.hasScout ? "Scouted" : "Missing"}</strong><span>{match.hasScout ? `Fuel ${value(match.totalFuel)}` : "No submitted report"}</span></div><div className="team-timeline-actions">{match.reportUrl && <Link className="link" href={match.reportUrl}>Report</Link>}{match.tbaUrl && <Link className="link" href={match.tbaUrl} target="_blank">TBA ↗</Link>}</div></article>)}</div></> : <p className="muted">No matches have been published for this team yet.</p>}</section>;
}
