"use client";

import { useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Props = { eventId: string; matchId: string; teamId: string; assignmentId?: string; teamNumber: number; alliance?: "red" | "blue"; otherTeams: { id: string; number: number; alliance: "red" | "blue" }[] };
const spots = ["Center", "Bump left", "Bump right", "Under trench left", "Under trench right", "Behind trench left", "Behind trench right"];
const breakTags = ["Intake broke", "Shooter broke", "Drive issue", "Electrical", "Other"];

export function RebuiltMatchForm({ eventId, matchId, teamId, assignmentId, teamNumber, alliance = "red", otherTeams }: Props) {
  const [noShow, setNoShow] = useState(false); const [spot, setSpot] = useState<string>(); const [autoFuel, setAutoFuel] = useState(0); const [teleFuel, setTeleFuel] = useState(0); const [fouls, setFouls] = useState(0); const [defense, setDefense] = useState(false); const [level, setLevel] = useState(5); const [defended, setDefended] = useState<string[]>([]); const [broke, setBroke] = useState(false); const [breakTag, setBreakTag] = useState<string>(); const [timestamp, setTimestamp] = useState(""); const [message, setMessage] = useState<string>(); const [saving, setSaving] = useState(false);
  const disabled = noShow || saving;
  const adjust = (setValue: (value:number)=>void, current:number, by:number) => setValue(Math.max(0, current + by));
  async function save(finalize=false) { setSaving(true); const supabase:any = createClient(); const {data:{user}}=await supabase.auth.getUser(); if (!user) {setMessage("Sign in again to save."); setSaving(false); return;} const payload={no_show:noShow,starting_spot:noShow?null:spot,auto_fuel:noShow?0:autoFuel,teleop_fuel:noShow?0:teleFuel,fouls:noShow?0:fouls,defense:noShow?false:defense,defense_level:defense?level:null,defended_teams:defense?defended:[],robot_broke:noShow?false:broke,break_timestamp:broke?timestamp:null,break_tag:broke?breakTag:null}; const {error}=await supabase.from("scouting_entries").insert({event_id:eventId,team_id:teamId,match_id:matchId,assignment_id:assignmentId??null,scout_user_id:user.id,entry_type:"match",form_version:1,payload,status:finalize?"submitted":"draft",submitted_at:finalize?new Date().toISOString():null,organization_id:(await supabase.from("organization_members").select("organization_id").eq("user_id",user.id).limit(1).single()).data?.organization_id}); setMessage(error?"Could not save. Check your connection.":finalize?"Match entry submitted.":"Draft saved."); setSaving(false); }
  return <div className="card"><div className="card-head"><div><h2>2026 REBUILT match scout</h2><p className="muted">Team {teamNumber} · {alliance} alliance</p></div><button className="button secondary" onClick={()=>setNoShow(!noShow)}>{noShow?"Undo no show":"No show"}</button></div><fieldset disabled={disabled} style={{border:0,padding:0,margin:0}}><div className={`field-map ${alliance === "blue" ? "flipped" : ""}`}>{spots.map((label)=><button key={label} type="button" className={spot===label?`spot ${alliance}`:"spot"} onClick={()=>setSpot(label)}>{label}</button>)}</div><p className="muted">Select one starting position. The field orientation flips for blue alliance.</p><div className="form-grid"><Counter label="Auto fuel scored / ferried" value={autoFuel} by={10} setValue={setAutoFuel}/><Counter label="Teleop fuel scored / ferried" value={teleFuel} by={10} setValue={setTeleFuel}/><Counter label="Fouls" value={fouls} by={1} setValue={setFouls}/></div><div className="section"><label><input type="checkbox" checked={defense} onChange={e=>setDefense(e.target.checked)}/> Played defense</label>{defense&&<><div className="field"><label>Defense level: {level} / 10</label><input type="range" min="1" max="10" value={level} onChange={e=>setLevel(Number(e.target.value))}/></div><div className="team-picker">{otherTeams.map(team=><button type="button" key={team.id} className={defended.includes(team.id)?`team-pick ${team.alliance}`:"team-pick"} onClick={()=>setDefended(current=>current.includes(team.id)?current.filter(id=>id!==team.id):[...current,team.id])}>{team.number}</button>)}</div></>}</div><div className="section"><label><input type="checkbox" checked={broke} onChange={e=>setBroke(e.target.checked)}/> Robot broke</label>{broke&&<div className="form-grid"><div className="field"><label>Match timestamp (optional)</label><input value={timestamp} onChange={e=>setTimestamp(e.target.value)} placeholder="e.g. 1:42"/></div><div className="field"><label>PulseCrew tag</label><select value={breakTag??""} onChange={e=>setBreakTag(e.target.value)}><option value="">Select…</option>{breakTags.map(tag=><option key={tag}>{tag}</option>)}</select></div></div>}</div></fieldset>{noShow&&<p className="trend">No-show selected: scoring and match details are recorded as empty.</p>}<div style={{display:"flex",justifyContent:"flex-end",gap:10,marginTop:18}}><button className="button secondary" onClick={()=>save(false)} disabled={saving}>Save draft</button><button className="button" onClick={()=>save(true)} disabled={saving}>{saving?"Saving…":"Submit match"}</button></div>{message&&<p className="trend">{message}</p>}</div>;
}
function Counter({label,value,by,setValue}:{label:string;value:number;by:number;setValue:(value:number)=>void}){return <div className="field"><label>{label}</label><div className="counter"><button type="button" onClick={()=>setValue(Math.max(0,value-by))}>−</button><input aria-label={label} type="number" min="0" value={value} onChange={e=>setValue(Math.max(0,Number(e.target.value)))}/><button type="button" onClick={()=>setValue(value+by)}>+</button></div></div>}
