"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

type Row = { team: { team_number: number; name: string }; teamId: string; tba: any; opr: number; maxFuel: number; autoClimb: string; autoClimbRate: number; endgameClimb: string; endgameClimbRate: number; tbaTotalFuel: number; tbaAutoFuel: number; tbaTransitionFuel: number; tbaTeleopFuel: number; tbaEndgameFuel: number; stats: Record<string, number> };
type Column = { key: string; label: string; render: (row: Row) => string | number; sortable?: boolean };
const number = (value: number) => value.toFixed(2);
const groups: Record<string, { label: string; columns: Column[] }> = {
  overview: { label: "Summary", columns: [{ key: "rank", label: "Rank", render: (row) => row.tba?.rank ?? "—" }, { key: "team", label: "Team", render: (row) => `${row.team.team_number} · ${row.team.name}` }, { key: "record", label: "W–L–T", sortable: false, render: (row) => row.tba?.record ? `${row.tba.record.wins}-${row.tba.record.losses}-${row.tba.record.ties}` : "—" }, { key: "opr", label: "OPR", render: (row) => number(row.opr) }, { key: "tbaTotalFuel", label: "TBA total fuel", render: (row) => number(row.tbaTotalFuel) }, { key: "tbaAutoFuel", label: "TBA auto fuel", render: (row) => number(row.tbaAutoFuel) }, { key: "tbaTransitionFuel", label: "TBA transition fuel", render: (row) => number(row.tbaTransitionFuel) }, { key: "tbaTeleopFuel", label: "TBA teleop fuel", render: (row) => number(row.tbaTeleopFuel) }, { key: "tbaEndgameFuel", label: "TBA endgame fuel", render: (row) => number(row.tbaEndgameFuel) }, { key: "entries", label: "Reports", render: (row) => row.stats.entries }, { key: "totalFuel", label: "Scout total fuel", render: (row) => number(row.stats.totalFuel) }] },
  performance: { label: "Performance", columns: [{ key: "rank", label: "Rank", render: (row) => row.tba?.rank ?? "—" }, { key: "team", label: "Team", render: (row) => `${row.team.team_number} · ${row.team.name}` }, { key: "autoClimb", label: "Typical auto climb", sortable: false, render: (row) => row.autoClimb }, { key: "autoClimbRate", label: "Auto climb success", render: (row) => `${number(row.autoClimbRate)}%` }, { key: "endgameClimb", label: "Typical endgame climb", sortable: false, render: (row) => row.endgameClimb }, { key: "endgameClimbRate", label: "Endgame climb success", render: (row) => `${number(row.endgameClimbRate)}%` }, { key: "maxFuel", label: "Max fuel scored", render: (row) => number(row.maxFuel) }, { key: "autoMaxFerried", label: "Auto max ferried", render: (row) => number(row.stats.autoMaxFerried) }, { key: "teleopMaxFerried", label: "Teleop max ferried", render: (row) => number(row.stats.teleopMaxFerried) }, { key: "avgFouls", label: "Avg fouls", render: (row) => number(row.stats.avgFouls) }, { key: "defense", label: "Defense", render: (row) => number(row.stats.defense) }, { key: "brokenPercent", label: "% broken", render: (row) => number(row.stats.brokenPercent) }] },
  auton: { label: "Auton", columns: [{ key: "rank", label: "Rank", render: (row) => row.tba?.rank ?? "—" }, { key: "team", label: "Team", render: (row) => `${row.team.team_number} · ${row.team.name}` }, { key: "autoMaxScored", label: "Max scored", render: (row) => number(row.stats.autoMaxScored) }, { key: "autoMaxFerried", label: "Max ferried", render: (row) => number(row.stats.autoMaxFerried) }, { key: "autoAvgScored", label: "Avg scored", render: (row) => number(row.stats.autoAvgScored) }, { key: "autoAvgFerried", label: "Avg ferried", render: (row) => number(row.stats.autoAvgFerried) }, { key: "autoFuel", label: "Avg total fuel", render: (row) => number(row.stats.autoFuel) }] },
  teleop: { label: "Teleop", columns: [{ key: "rank", label: "Rank", render: (row) => row.tba?.rank ?? "—" }, { key: "team", label: "Team", render: (row) => `${row.team.team_number} · ${row.team.name}` }, { key: "teleopMaxScored", label: "Max scored", render: (row) => number(row.stats.teleopMaxScored) }, { key: "teleopMaxFerried", label: "Max ferried", render: (row) => number(row.stats.teleopMaxFerried) }, { key: "teleopAvgScored", label: "Avg scored", render: (row) => number(row.stats.teleopAvgScored) }, { key: "teleopAvgFerried", label: "Avg ferried", render: (row) => number(row.stats.teleopAvgFerried) }, { key: "teleopFuel", label: "Avg total fuel", render: (row) => number(row.stats.teleopFuel) }] },
  reliability: { label: "Reliability", columns: [{ key: "rank", label: "Rank", render: (row) => row.tba?.rank ?? "—" }, { key: "team", label: "Team", render: (row) => `${row.team.team_number} · ${row.team.name}` }, { key: "entries", label: "Reports", render: (row) => row.stats.entries }, { key: "avgFouls", label: "Avg fouls", render: (row) => number(row.stats.avgFouls) }, { key: "defense", label: "Defense", render: (row) => number(row.stats.defense) }, { key: "brokenPercent", label: "% broken", render: (row) => number(row.stats.brokenPercent) }] },
};

export function SummaryTable({ eventKey, rows, sort, dir }: { eventKey: string; rows: Row[]; sort: string; dir: string }) {
  const [group, setGroup] = useState("overview");
  const [teamFilter, setTeamFilter] = useState("");
  const current = groups[group];
  const activeColumn = Object.values(groups).flatMap((item) => item.columns).find((column) => column.key === sort);
  const visibleRows = useMemo(() => rows.filter((row) => `${row.team.team_number} ${row.team.name}`.toLowerCase().includes(teamFilter.trim().toLowerCase())), [rows, teamFilter]);
  const sortHref = (key: string) => `/events/${eventKey}/summary?sort=${key}&dir=${sort === key && dir === "asc" ? "desc" : "asc"}`;
  const sortState = `${activeColumn?.label ?? "Rank"}, ${dir === "asc" ? "lowest first" : "highest first"}`;

  return <><div className="summary-tabs" role="tablist" aria-label="Summary metric groups">{Object.entries(groups).map(([key, item]) => <button key={key} type="button" role="tab" aria-selected={group === key} className={group === key ? "active" : ""} onClick={() => setGroup(key)}>{item.label}</button>)}</div><div className="summary-controls"><label><span>Filter teams</span><input value={teamFilter} onChange={(event) => setTeamFilter(event.target.value)} placeholder="Search number or name…"/></label><div className="summary-sort-state" aria-live="polite"><span>Sorted by</span><strong>{sortState}</strong></div>{teamFilter && <button type="button" className="button secondary" onClick={() => setTeamFilter("")}>Clear filter</button>}<span className="muted">{visibleRows.length} of {rows.length} teams</span></div><div className="summary-mobile-list">{visibleRows.map((row) => <Link className="summary-mobile-card" href={`/events/${eventKey}/teams/${row.team.team_number}`} key={row.teamId}><div className="summary-mobile-heading"><div><strong>{row.team.team_number}</strong><span>{row.team.name}</span></div>{row.tba?.rank && <span className="rank">Rank {row.tba.rank}</span>}</div><div className="summary-mobile-metrics">{current.columns.filter((column) => column.key !== "team" && column.key !== "rank").map((column) => <div key={column.key}><span>{column.label}</span><strong>{column.render(row)}</strong></div>)}</div><span className="summary-open">Team details →</span></Link>)}</div><div className="table-scroll summary-table"><table><thead><tr>{current.columns.map((column) => <th key={column.key}>{column.sortable === false ? column.label : <Link className={sort === column.key ? "summary-sort-active" : ""} aria-label={`Sort by ${column.label}; currently ${sort === column.key ? (dir === "asc" ? "lowest first" : "highest first") : "not selected"}`} href={sortHref(column.key)}>{column.label}{sort === column.key && <span aria-hidden="true"> {dir === "asc" ? "↑" : "↓"}</span>}</Link>}</th>)}<th/></tr></thead><tbody>{visibleRows.map((row) => <tr key={row.teamId}>{current.columns.map((column) => <td key={column.key} className={column.key === "team" ? "summary-team" : ""}>{column.render(row)}</td>)}<td><Link className="link" href={`/events/${eventKey}/teams/${row.team.team_number}`}>Open →</Link></td></tr>)}</tbody></table></div>{!visibleRows.length && <p className="muted summary-empty">No teams match that filter.</p>}</>;
}
