"use client";

import Link from "next/link";
import { useState } from "react";

type Row = { team: { team_number: number; name: string }; teamId: string; tba: any; opr: number; tbaTotalFuel: number; tbaAutoFuel: number; tbaTeleopFuel: number; stats: Record<string, number> };
type Column = { key: string; label: string; render: (row: Row) => string | number };
const number = (value: number) => value.toFixed(2);
const groups: Record<string, { label: string; columns: Column[] }> = {
  overview: { label: "Overview", columns: [{ key: "rank", label: "Rank", render: (row) => row.tba?.rank ?? "—" }, { key: "team", label: "Team", render: (row) => `${row.team.team_number} · ${row.team.name}` }, { key: "record", label: "W–L–T", render: (row) => row.tba?.record ? `${row.tba.record.wins}-${row.tba.record.losses}-${row.tba.record.ties}` : "—" }, { key: "opr", label: "OPR", render: (row) => number(row.opr) }, { key: "tbaTotalFuel", label: "TBA total fuel", render: (row) => number(row.tbaTotalFuel) }, { key: "tbaAutoFuel", label: "TBA auto fuel", render: (row) => number(row.tbaAutoFuel) }, { key: "tbaTeleopFuel", label: "TBA teleop fuel", render: (row) => number(row.tbaTeleopFuel) }, { key: "entries", label: "Reports", render: (row) => row.stats.entries }, { key: "totalFuel", label: "Scout total fuel", render: (row) => number(row.stats.totalFuel) }, { key: "defense", label: "Defense", render: (row) => number(row.stats.defense) }] },
  auton: { label: "Auton", columns: [{ key: "rank", label: "Rank", render: (row) => row.tba?.rank ?? "—" }, { key: "team", label: "Team", render: (row) => `${row.team.team_number} · ${row.team.name}` }, { key: "autoMaxScored", label: "Max scored", render: (row) => number(row.stats.autoMaxScored) }, { key: "autoMaxFerried", label: "Max ferried", render: (row) => number(row.stats.autoMaxFerried) }, { key: "autoAvgScored", label: "Avg scored", render: (row) => number(row.stats.autoAvgScored) }, { key: "autoAvgFerried", label: "Avg ferried", render: (row) => number(row.stats.autoAvgFerried) }, { key: "autoFuel", label: "Avg total fuel", render: (row) => number(row.stats.autoFuel) }] },
  teleop: { label: "Teleop", columns: [{ key: "rank", label: "Rank", render: (row) => row.tba?.rank ?? "—" }, { key: "team", label: "Team", render: (row) => `${row.team.team_number} · ${row.team.name}` }, { key: "teleopMaxScored", label: "Max scored", render: (row) => number(row.stats.teleopMaxScored) }, { key: "teleopMaxFerried", label: "Max ferried", render: (row) => number(row.stats.teleopMaxFerried) }, { key: "teleopAvgScored", label: "Avg scored", render: (row) => number(row.stats.teleopAvgScored) }, { key: "teleopAvgFerried", label: "Avg ferried", render: (row) => number(row.stats.teleopAvgFerried) }, { key: "teleopFuel", label: "Avg total fuel", render: (row) => number(row.stats.teleopFuel) }] },
  reliability: { label: "Reliability", columns: [{ key: "rank", label: "Rank", render: (row) => row.tba?.rank ?? "—" }, { key: "team", label: "Team", render: (row) => `${row.team.team_number} · ${row.team.name}` }, { key: "entries", label: "Reports", render: (row) => row.stats.entries }, { key: "avgFouls", label: "Avg fouls", render: (row) => number(row.stats.avgFouls) }, { key: "defense", label: "Defense", render: (row) => number(row.stats.defense) }, { key: "brokenPercent", label: "% broken", render: (row) => number(row.stats.brokenPercent) }] },
};
export function SummaryTable({ eventKey, rows, sort, dir }: { eventKey: string; rows: Row[]; sort: string; dir: string }) { const [group, setGroup] = useState("overview"); const current = groups[group]; function href(key: string) { return `/events/${eventKey}/summary?sort=${key}&dir=${sort === key && dir !== "asc" ? "asc" : "desc"}`; } return <><div className="summary-tabs" role="tablist">{Object.entries(groups).map(([key, item]) => <button key={key} type="button" className={group === key ? "active" : ""} onClick={() => setGroup(key)}>{item.label}</button>)}</div><div className="table-scroll summary-table"><table><thead><tr>{current.columns.map((column) => <th key={column.key}>{column.key === "record" ? column.label : <Link href={href(column.key)}>{column.label}</Link>}</th>)}<th/></tr></thead><tbody>{rows.map((row) => <tr key={row.teamId}>{current.columns.map((column) => <td key={column.key} className={column.key === "team" ? "summary-team" : ""}>{column.render(row)}</td>)}<td><Link className="link" href={`/events/${eventKey}/teams/${row.team.team_number}`}>Open →</Link></td></tr>)}</tbody></table></div></>; }
