"use client";

import { useState } from "react";
import { formatStat, SCOUT_STAT_LABELS, type ScoutStats } from "@/lib/scouting-stats";
import { StatsGraph } from "@/components/stats-graph";

type TeamData = { number: number; name: string; color: string; rank: number | null; record: string; opr: number; tbaTotalFuel: number; tbaAutoFuel: number; tbaTeleopFuel: number; stats: ScoutStats };
const scoutKeys = ["totalFuel", "autoFuel", "teleopFuel", "autoMaxScored", "autoMaxFerried", "autoAvgScored", "autoAvgFerried", "teleopMaxScored", "teleopMaxFerried", "teleopAvgScored", "teleopAvgFerried", "avgFouls", "defense", "brokenPercent"] as const;
export function CompareMetrics({ left, right }: { left: TeamData; right: TeamData }) { const [view, setView] = useState<"official" | "scouting">("official"); const official = [["Rank", left.rank ?? "—", right.rank ?? "—"], ["Record", left.record, right.record], ["OPR", formatStat(left.opr), formatStat(right.opr)], ["TBA total fuel", formatStat(left.tbaTotalFuel), formatStat(right.tbaTotalFuel)], ["TBA auto fuel", formatStat(left.tbaAutoFuel), formatStat(right.tbaAutoFuel)], ["TBA teleop fuel", formatStat(left.tbaTeleopFuel), formatStat(right.tbaTeleopFuel)]]; const scouting = [["Reports", left.stats.entries, right.stats.entries], ...scoutKeys.map((key) => [SCOUT_STAT_LABELS[key], formatStat(left.stats[key]), formatStat(right.stats[key])])]; const metrics = view === "official" ? official : scouting; return <><section className="card section compare-card"><div className="compare-team-heading"><div><span className="compare-dot red"/><strong>{left.number}</strong><small>{left.name}</small></div><span>vs</span><div><span className="compare-dot blue"/><strong>{right.number}</strong><small>{right.name}</small></div></div><div className="summary-tabs"><button className={view === "official" ? "active" : ""} type="button" onClick={() => setView("official")}>Official TBA</button><button className={view === "scouting" ? "active" : ""} type="button" onClick={() => setView("scouting")}>Scout reports</button></div><div className="comparison-table"><div className="comparison-head"><span>Metric</span><strong>{left.number}</strong><strong>{right.number}</strong></div>{metrics.map(([label, a, b]) => <div className="comparison-metric" key={String(label)}><span>{label}</span><strong data-team={left.number}>{a}</strong><strong data-team={right.number}>{b}</strong></div>)}</div></section>{view === "scouting" && <StatsGraph series={[{ label: String(left.number), color: left.color, stats: left.stats }, { label: String(right.number), color: right.color, stats: right.stats }]}/>}</> }
