"use client";

import { useState } from "react";
import { formatStat, type ScoutStats } from "@/lib/scouting-stats";
import { StatsGraph } from "@/components/stats-graph";

type TeamData = { number: number; name: string; photoUrl: string | null; color: string; rank: number | null; record: string; opr: number; tbaTotalFuel: number; tbaAutoFuel: number; tbaTransitionFuel: number; tbaTeleopFuel: number; tbaEndgameFuel: number; maxFuel: number; autoClimb: string; autoClimbRate: number; endgameClimb: string; endgameClimbRate: number; stats: ScoutStats };
type View = "overview" | "performance" | "auton" | "teleop" | "reliability";
type Metric = [string, string | number, string | number];
const scout = (team: TeamData, key: keyof ScoutStats) => formatStat(team.stats[key]);

export function CompareMetrics({ left, right }: { left: TeamData; right: TeamData }) {
  const [view, setView] = useState<View>("overview");
  const groups: Record<View, { label: string; metrics: Metric[] }> = {
    overview: { label: "Summary", metrics: [["Rank", left.rank ?? "—", right.rank ?? "—"], ["W–L–T", left.record, right.record], ["OPR", formatStat(left.opr), formatStat(right.opr)], ["TBA total fuel", formatStat(left.tbaTotalFuel), formatStat(right.tbaTotalFuel)], ["TBA auto fuel", formatStat(left.tbaAutoFuel), formatStat(right.tbaAutoFuel)], ["TBA transition fuel", formatStat(left.tbaTransitionFuel), formatStat(right.tbaTransitionFuel)], ["TBA teleop fuel", formatStat(left.tbaTeleopFuel), formatStat(right.tbaTeleopFuel)], ["TBA endgame fuel", formatStat(left.tbaEndgameFuel), formatStat(right.tbaEndgameFuel)], ["Reports", left.stats.entries, right.stats.entries], ["Scout total fuel", scout(left, "totalFuel"), scout(right, "totalFuel")]] },
    performance: { label: "Performance", metrics: [["Typical auto climb", left.autoClimb, right.autoClimb], ["Auto climb success", `${formatStat(left.autoClimbRate)}%`, `${formatStat(right.autoClimbRate)}%`], ["Typical endgame climb", left.endgameClimb, right.endgameClimb], ["Endgame climb success", `${formatStat(left.endgameClimbRate)}%`, `${formatStat(right.endgameClimbRate)}%`], ["Max fuel scored", formatStat(left.maxFuel), formatStat(right.maxFuel)], ["Auto max ferried", scout(left, "autoMaxFerried"), scout(right, "autoMaxFerried")], ["Teleop max ferried", scout(left, "teleopMaxFerried"), scout(right, "teleopMaxFerried")], ["Avg fouls", scout(left, "avgFouls"), scout(right, "avgFouls")], ["Defense", scout(left, "defense"), scout(right, "defense")], ["% broken", scout(left, "brokenPercent"), scout(right, "brokenPercent")]] },
    auton: { label: "Auton", metrics: [["Max scored", scout(left, "autoMaxScored"), scout(right, "autoMaxScored")], ["Max ferried", scout(left, "autoMaxFerried"), scout(right, "autoMaxFerried")], ["Avg scored", scout(left, "autoAvgScored"), scout(right, "autoAvgScored")], ["Avg ferried", scout(left, "autoAvgFerried"), scout(right, "autoAvgFerried")], ["Avg total fuel", scout(left, "autoFuel"), scout(right, "autoFuel")]] },
    teleop: { label: "Teleop", metrics: [["Max scored", scout(left, "teleopMaxScored"), scout(right, "teleopMaxScored")], ["Max ferried", scout(left, "teleopMaxFerried"), scout(right, "teleopMaxFerried")], ["Avg scored", scout(left, "teleopAvgScored"), scout(right, "teleopAvgScored")], ["Avg ferried", scout(left, "teleopAvgFerried"), scout(right, "teleopAvgFerried")], ["Avg total fuel", scout(left, "teleopFuel"), scout(right, "teleopFuel")]] },
    reliability: { label: "Reliability", metrics: [["Reports", left.stats.entries, right.stats.entries], ["Avg fouls", scout(left, "avgFouls"), scout(right, "avgFouls")], ["Defense", scout(left, "defense"), scout(right, "defense")], ["% broken", scout(left, "brokenPercent"), scout(right, "brokenPercent")]] },
  };
  const metrics = groups[view].metrics;
  return <><section className="card section compare-card"><div className="compare-team-heading"><div className="compare-team-card"><div className="compare-team-photo">{left.photoUrl ? <img src={left.photoUrl} alt={`${left.number} robot`} /> : <span>No pit photo</span>}</div><div><span className="compare-dot red"/><strong>{left.number}</strong><small>{left.name}</small></div></div><span>vs</span><div className="compare-team-card"><div className="compare-team-photo">{right.photoUrl ? <img src={right.photoUrl} alt={`${right.number} robot`} /> : <span>No pit photo</span>}</div><div><span className="compare-dot blue"/><strong>{right.number}</strong><small>{right.name}</small></div></div></div><div className="summary-tabs" role="tablist" aria-label="Comparison metric groups">{(Object.entries(groups) as [View, typeof groups[View]][]).map(([key, group]) => <button key={key} className={view === key ? "active" : ""} type="button" role="tab" aria-selected={view === key} onClick={() => setView(key)}>{group.label}</button>)}</div><div className="comparison-table"><div className="comparison-head"><span>Metric</span><strong>{left.number}</strong><strong>{right.number}</strong></div>{metrics.map(([label, a, b]) => <div className="comparison-metric" key={String(label)}><span>{label}</span><strong data-team={left.number}>{a}</strong><strong data-team={right.number}>{b}</strong></div>)}</div></section>{view !== "overview" && <StatsGraph series={[{ label: String(left.number), color: left.color, stats: left.stats }, { label: String(right.number), color: right.color, stats: right.stats }]}/>}</>;
}
