"use client";

import Link from "next/link";
import { useActionState, useMemo, useState } from "react";
import { createPracticeMatch, type ActionState } from "@/lib/admin-actions";
import { formatLocalDateTime } from "@/components/local-date-time";

type Match = { id: string; key: string; number: number; type: string; red: string[]; blue: string[]; scheduledAt: string | null; status: string; redScore: number | null; blueScore: number | null };
type Team = { id: string; number: number };
const initialActionState: ActionState = {};
const label = (match: Match) => { const suffix = match.key.split("_").pop() ?? ""; const qualification = suffix.match(/^qm(\d+)$/), final = suffix.match(/^f(\d+)m(\d+)$/), semifinal = suffix.match(/^sf(\d+)m(\d+)$/); return qualification ? `Q${qualification[1]}` : final ? `Final ${final[1]} M${final[2]}` : semifinal ? `SF ${semifinal[1]} M${semifinal[2]}` : match.type === "practice" ? `Practice ${match.number}` : suffix.toUpperCase(); };

function PracticeMatchSetup({ eventId }: { eventId: string }) { const [state, action, pending] = useActionState(createPracticeMatch, initialActionState); return <details className="practice-setup"><summary>Add a local practice match</summary><p className="muted">Enter the teams manually, including filler teams. This creates a local-only practice record; TBA is read-only and never receives it.</p><form action={action} className="practice-match-form"><input type="hidden" name="eventId" value={eventId}/><div className="field"><label>Practice match #</label><input name="matchNumber" type="number" min="1" required placeholder="1"/></div><div className="field"><label>Red team numbers</label><input name="redTeams" required placeholder="694, 1678, 254"/></div><div className="field"><label>Blue team numbers</label><input name="blueTeams" required placeholder="118, 6328, 971"/></div><button className="button" disabled={pending}>{pending ? "Adding…" : "Add practice match"}</button></form>{state.error && <p className="error">{state.error}</p>}{state.success && <p className="trend">{state.success}</p>}</details>; }

export function MatchesBoard({ matches, teams, eventId, canManage }: { matches: Match[]; teams: Team[]; eventId: string; canManage: boolean }) {
  const [type, setType] = useState("all"), [teamId, setTeamId] = useState(""), [status, setStatus] = useState("all");
  const number = new Map(teams.map((team) => [team.id, team.number]));
  const shown = useMemo(() => matches.filter((match) => (type === "all" || match.type === type) && (!teamId || [...match.red, ...match.blue].includes(teamId)) && (status === "all" || match.status === status)), [matches, type, teamId, status]);
  const completed = matches.filter((match) => match.status === "played").length;
  const upcoming = matches.filter((match) => match.status !== "played" && match.status !== "cancelled").length;
  return <section className="card"><div className="card-head"><div><h2>Match schedule</h2><p className="muted">Official schedule and final scores refresh automatically while the active event is open.</p></div><span className="muted">{upcoming} left · {completed} complete</span></div>{canManage && <PracticeMatchSetup eventId={eventId}/>}<div className="schedule-filters"><select value={type} onChange={(event) => setType(event.target.value)}><option value="all">All rounds</option><option value="qualification">Qualifications</option><option value="playoff">Playoffs</option><option value="practice">Practice</option></select><select value={teamId} onChange={(event) => setTeamId(event.target.value)}><option value="">All teams</option>{[...teams].sort((a, b) => a.number - b.number).map((team) => <option key={team.id} value={team.id}>{team.number}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option><option value="scheduled">Upcoming</option><option value="played">Finished</option></select></div>{shown.map((match) => <div className="match-row" key={match.id}><span className="match-time">{match.scheduledAt ? formatLocalDateTime(match.scheduledAt, "time") : "—"}</span><span className="match-num">{label(match)}</span><div className="alliances"><div className="red">{match.red.map((id) => number.get(id) ?? "—").join(" · ")}</div><div className="blue">{match.blue.map((id) => number.get(id) ?? "—").join(" · ")}</div></div>{match.redScore !== null && match.blueScore !== null ? <span className="match-score" aria-label={`Final score: red ${match.redScore}, blue ${match.blueScore}`}><span className="red">{match.redScore}</span><span>–</span><span className="blue">{match.blueScore}</span></span> : <span className={`tag ${match.status === "played" ? "complete" : "pending"}`}>{match.status}</span>}<Link className="button secondary" href={`/scout/match?match=${match.id}`}>Scout</Link></div>)}{!shown.length && <p className="muted">No matches match these filters.</p>}</section>;
}
