"use client";

import Link from "next/link";
import { useActionState, useMemo, useState } from "react";
import { addManualEventTeam, createPracticeMatch, deleteManualMatch, removeManualEventTeam, saveManualMatch, type ActionState } from "@/lib/admin-actions";
import { formatLocalDateTime } from "@/components/local-date-time";
import { SearchableTeamSelect } from "@/components/searchable-team-select";

type Match = { id: string; key: string; number: number; type: string; red: string[]; blue: string[]; scheduledAt: string | null; status: string; redScore: number | null; blueScore: number | null };
type Team = { id: string; number: number; name: string };
const initialActionState: ActionState = {};
const label = (match: Match) => match.type === "qualification" ? `Q${match.number}` : match.type === "practice" ? `Practice ${match.number}` : `${match.type} ${match.number}`;
const teamNumbers = (ids: string[], teams: Team[]) => ids.map((id) => teams.find((team) => team.id === id)?.number ?? "—").join(", ");
const localInputValue = (value: string | null) => value ? new Date(value).toISOString().slice(0, 16) : "";
function Message({ state }: { state: ActionState }) { return state.error ? <p className="error">{state.error}</p> : state.success ? <p className="trend">{state.success}</p> : null; }

function PracticeMatchSetup({ eventId }: { eventId: string }) { const [state, action, pending] = useActionState(createPracticeMatch, initialActionState); return <details className="practice-setup"><summary>Add a local practice match</summary><p className="muted">Enter the teams manually, including filler teams. This creates a local-only practice record; TBA is read-only and never receives it.</p><form action={action} className="practice-match-form"><input type="hidden" name="eventId" value={eventId}/><div className="field"><label>Practice match #</label><input name="matchNumber" type="text" inputMode="numeric" pattern="[0-9]*" required placeholder="1"/></div><div className="field"><label>Red team numbers</label><input name="redTeams" required placeholder="694, 1678, 254"/></div><div className="field"><label>Blue team numbers</label><input name="blueTeams" required placeholder="118, 6328, 971"/></div><button className="button" disabled={pending}>{pending ? "Adding…" : "Add practice match"}</button></form><Message state={state}/></details>; }

function ManualTeamRow({ eventId, team }: { eventId: string; team: Team }) { const [state, action, pending] = useActionState(removeManualEventTeam, initialActionState); return <div className="manual-team-row"><span><strong>{team.number}</strong> · {team.name}</span><form action={action}><input type="hidden" name="eventId" value={eventId}/><input type="hidden" name="teamId" value={team.id}/><button type="submit" className="button secondary" disabled={pending}>Remove</button></form>{state.error && <span className="error">{state.error}</span>}</div>; }

function ManualRoster({ eventId, teams }: { eventId: string; teams: Team[] }) { const [state, action, pending] = useActionState(addManualEventTeam, initialActionState); return <section className="manual-event-section"><div><h3>Event teams</h3><p className="muted">Add a team to this event, or enter an existing team number to update its name.</p></div><form action={action} className="manual-team-form"><input type="hidden" name="eventId" value={eventId}/><label><span>Team #</span><input name="teamNumber" type="text" inputMode="numeric" pattern="[0-9]*" required placeholder="694"/></label><label><span>Name</span><input name="name" required maxLength={160} placeholder="Stuy Fission"/></label><button className="button secondary" disabled={pending}>{pending ? "Saving…" : "Save team"}</button></form><Message state={state}/><div className="manual-team-list">{teams.length ? teams.map((team) => <ManualTeamRow key={team.id} eventId={eventId} team={team}/>) : <p className="muted">No teams added yet.</p>}</div></section>; }

function ManualMatchSetup({ eventId, teams, matches }: { eventId: string; teams: Team[]; matches: Match[] }) { const [editing, setEditing] = useState<Match | null>(null); const [state, action, pending] = useActionState(saveManualMatch, initialActionState); const [deleteState, deleteAction, deleting] = useActionState(deleteManualMatch, initialActionState); return <section className="manual-event-section"><div className="card-head"><div><h3>{editing ? `Edit ${label(editing)}` : "Add a match"}</h3><p className="muted">Teams are saved to the event automatically. Enter one to three teams per alliance.</p></div>{editing && <button type="button" className="button secondary" onClick={() => setEditing(null)}>New match</button>}</div><form key={editing?.id ?? "new"} action={action} className="manual-match-form"><input type="hidden" name="eventId" value={eventId}/><input type="hidden" name="matchId" value={editing?.id ?? ""}/><label><span>Match #</span><input name="matchNumber" type="text" inputMode="numeric" pattern="[0-9]*" required defaultValue={editing?.number ?? ""}/></label><label><span>Round</span><select name="matchType" defaultValue={editing?.type ?? "qualification"}><option value="qualification">Qualification</option><option value="playoff">Playoff</option><option value="practice">Practice</option></select></label><label><span>Scheduled time</span><input name="scheduledAt" type="datetime-local" defaultValue={localInputValue(editing?.scheduledAt ?? null)}/></label><label><span>Red teams</span><input name="redTeams" required defaultValue={editing ? teamNumbers(editing.red, teams) : ""} placeholder="694, 1678, 254"/></label><label><span>Blue teams</span><input name="blueTeams" required defaultValue={editing ? teamNumbers(editing.blue, teams) : ""} placeholder="118, 6328, 971"/></label><button className="button" disabled={pending}>{pending ? "Saving…" : editing ? "Save match" : "Add match"}</button></form><Message state={state}/>{editing && <form action={deleteAction} onSubmit={(event) => { if (!window.confirm(`Delete ${label(editing)}?`)) event.preventDefault(); }}><input type="hidden" name="eventId" value={eventId}/><input type="hidden" name="matchId" value={editing.id}/><button className="button danger" disabled={deleting}>{deleting ? "Deleting…" : "Delete match"}</button><Message state={deleteState}/></form>}<div className="manual-match-list">{matches.map((match) => <button type="button" key={match.id} className={editing?.id === match.id ? "active" : ""} onClick={() => setEditing(match)}><strong>{label(match)}</strong><span>{teamNumbers(match.red, teams)} vs {teamNumbers(match.blue, teams)}</span></button>)}</div></section>; }

function ManualEventSetup({ eventId, teams, matches }: { eventId: string; teams: Team[]; matches: Match[] }) { return <section className="card manual-event-setup"><div className="card-head"><div><h2>Manual event setup</h2><p className="muted">This event stays fully local to HAL9000. It will not sync with The Blue Alliance.</p></div></div><ManualRoster eventId={eventId} teams={teams}/><ManualMatchSetup eventId={eventId} teams={teams} matches={matches}/></section>; }

export function MatchesBoard({ matches, teams, eventId, isManual, canManage }: { matches: Match[]; teams: Team[]; eventId: string; isManual: boolean; canManage: boolean }) { const [type, setType] = useState("all"), [teamId, setTeamId] = useState(""), [status, setStatus] = useState("all"); const number = new Map(teams.map((team) => [team.id, team.number])); const shown = useMemo(() => matches.filter((match) => (type === "all" || match.type === type) && (!teamId || [...match.red, ...match.blue].includes(teamId)) && (status === "all" || match.status === status)), [matches, type, teamId, status]); const completed = matches.filter((match) => match.status === "played").length; const upcoming = matches.filter((match) => match.status !== "played" && match.status !== "cancelled").length; return <>{canManage && isManual && <ManualEventSetup eventId={eventId} teams={teams} matches={matches}/>}<section className="card"><div className="card-head"><div><h2>Match schedule</h2><p className="muted">{isManual ? "Locally managed schedule and scores." : "Official schedule and final scores refresh automatically while the active event is open."}</p></div><span className="muted">{upcoming} left · {completed} complete</span></div>{canManage && !isManual && <PracticeMatchSetup eventId={eventId}/>}<div className="schedule-filters"><select value={type} onChange={(event) => setType(event.target.value)}><option value="all">All rounds</option><option value="qualification">Qualifications</option><option value="playoff">Playoffs</option><option value="practice">Practice</option></select><SearchableTeamSelect id="schedule-team-filter" value={teamId} onValueChange={setTeamId} teams={teams.map((team) => ({ ...team, name: team.name }))} emptyLabel="All teams" placeholder="Search team…"/><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option><option value="scheduled">Upcoming</option><option value="played">Finished</option></select></div>{shown.map((match) => <div className="match-row" key={match.id}><span className="match-time">{match.scheduledAt ? formatLocalDateTime(match.scheduledAt, "time") : "—"}</span><span className="match-num">{label(match)}</span><div className="alliances"><div className="red">{match.red.map((id) => number.get(id) ?? "—").join(" · ")}</div><div className="blue">{match.blue.map((id) => number.get(id) ?? "—").join(" · ")}</div></div>{match.redScore !== null && match.blueScore !== null ? <span className="match-score" aria-label={`Final score: red ${match.redScore}, blue ${match.blueScore}`}><span className="red">{match.redScore}</span><span>–</span><span className="blue">{match.blueScore}</span></span> : <span className={`tag ${match.status === "played" ? "complete" : "pending"}`}>{match.status}</span>}<Link className="button secondary" href={`/scout/match?match=${match.id}`}>Scout</Link></div>)}{!shown.length && <p className="muted">No matches match these filters.</p>}</section></>; }
