"use server";
import { z } from "zod";
import { DEFAULT_2026_FORM, formDefinitionSchema, organizationRoleSchema } from "@wildcard/shared";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";

export type ActionState = { error?: string; success?: string };
async function adminContext() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error("Sign in required.");
  const { data: member } = await supabase.from("organization_members").select("organization_id, role").eq("user_id", user.id).in("role", ["admin", "developer"]).limit(1).maybeSingle();
  if (!member) throw new Error("Admin access required.");
  return { supabase, organizationId: member.organization_id };
}

export async function createEvent(_: ActionState, formData: FormData): Promise<ActionState> {
  try { const input=z.object({name:z.string().trim().min(3).max(160),eventKey:z.string().trim().regex(/^[0-9]{4}[a-z0-9_]+$/),startsAt:z.string().optional(),endsAt:z.string().optional()}).safeParse({name:formData.get("name"),eventKey:formData.get("eventKey"),startsAt:formData.get("startsAt")||undefined,endsAt:formData.get("endsAt")||undefined}); if(!input.success)return{error:"Use a valid TBA event key, such as 2026nytr."}; const {supabase,organizationId}=await adminContext();const {error}=await supabase.from("events").insert({organization_id:organizationId,name:input.data.name,event_key:input.data.eventKey,starts_at:input.data.startsAt||null,ends_at:input.data.endsAt||null,status:"upcoming"});return error?{error:"Couldn’t create the event."}:{success:"Event created."}; } catch { return {error:"Admin access is required."}; }
}

export async function publishDefaultForm(_: ActionState): Promise<ActionState> { try { const {supabase,organizationId}=await adminContext(); const {data:latest}=await supabase.from("form_definitions").select("version").eq("organization_id",organizationId).eq("name",DEFAULT_2026_FORM.title).order("version",{ascending:false}).limit(1).maybeSingle();const {error}=await supabase.from("form_definitions").insert({organization_id:organizationId,name:DEFAULT_2026_FORM.title,version:(latest?.version??0)+1,schema_json:DEFAULT_2026_FORM,is_active:true});return error?{error:"Couldn’t publish the form."}:{success:"New form version published."}; }catch{return{error:"Admin access is required."};} }

export async function publishFormDefinition(_: ActionState, formData: FormData): Promise<ActionState> { try { const raw=String(formData.get("schema")??"");let json:unknown;try{json=JSON.parse(raw)}catch{return{error:"The form schema must be valid JSON."};}const form=formDefinitionSchema.safeParse(json);if(!form.success)return{error:"The schema needs a title, game year, and valid field definitions."};const {supabase,organizationId}=await adminContext();const {data:latest}=await supabase.from("form_definitions").select("version").eq("organization_id",organizationId).eq("name",form.data.title).order("version",{ascending:false}).limit(1).maybeSingle();const {error}=await supabase.from("form_definitions").insert({organization_id:organizationId,name:form.data.title,version:(latest?.version??0)+1,schema_json:form.data,is_active:true});return error?{error:"Couldn’t publish the form."}:{success:`Published ${form.data.title} v${(latest?.version??0)+1}.`};}catch{return{error:"Admin access is required."};} }

export async function inviteMember(_: ActionState, formData: FormData): Promise<ActionState> { try {const input=z.object({email:z.string().email(),role:organizationRoleSchema}).safeParse({email:formData.get("email"),role:formData.get("role")});if(!input.success)return{error:"Enter a valid email and role."};const {supabase,organizationId}=await adminContext();const admin=createAdminClient();const origin=process.env.NEXT_PUBLIC_SITE_URL??"http://localhost:3000";const {data,error}=await admin.auth.admin.inviteUserByEmail(input.data.email,{redirectTo:`${origin}/auth/callback`});if(error||!data.user)return{error:"Couldn’t send the invitation."};const {error:membershipError}=await supabase.from("organization_members").upsert({organization_id:organizationId,user_id:data.user.id,role:input.data.role});return membershipError?{error:"Invitation sent, but the role assignment failed."}:{success:`Invitation sent to ${input.data.email}.`};}catch{return{error:"Admin access or server secret is required."};} }

type TbaTeam = { key:string; team_number:number; nickname:string | null };
type TbaMatch = { key:string; comp_level:string; match_number:number; set_number:number; time:number; actual_time:number|null; alliances:{red:{team_keys:string[]};blue:{team_keys:string[]}} };
export async function importTbaEvent(_: ActionState, formData: FormData): Promise<ActionState> { try {
  const parsed=z.object({eventKey:z.string().trim().regex(/^[0-9]{4}[a-z0-9_]+$/)}).safeParse({eventKey:formData.get("eventKey")}); if(!parsed.success)return{error:"Enter a valid TBA event key."};
  const key=process.env.TBA_AUTH_KEY;if(!key)return{error:"TBA_AUTH_KEY is not configured on the server."};const {supabase,organizationId}=await adminContext();
  const {data:existing}=await supabase.from("events").select("id,tba_etag").eq("organization_id",organizationId).eq("event_key",parsed.data.eventKey).maybeSingle();
  const eventResponse=await fetch(`https://www.thebluealliance.com/api/v3/event/${parsed.data.eventKey}`,{headers:{"X-TBA-Auth-Key":key,...(existing?.tba_etag?{"If-None-Match":existing.tba_etag}:{})},cache:"no-store"});
  if(eventResponse.status===304)return{success:"TBA reports no event changes since the last sync."};if(!eventResponse.ok)return{error:"TBA could not find or return that event."};
  const event=await eventResponse.json() as {name:string;start_date:string;end_date:string}; const etag=eventResponse.headers.get("etag");
  const {data:eventRow,error:eventError}=await supabase.from("events").upsert({organization_id:organizationId,event_key:parsed.data.eventKey,name:event.name,starts_at:`${event.start_date}T00:00:00Z`,ends_at:`${event.end_date}T23:59:59Z`,status:"upcoming",tba_etag:etag,tba_last_synced_at:new Date().toISOString()},{onConflict:"organization_id,event_key"}).select("id").single();if(eventError||!eventRow)return{error:"Couldn’t save the event."};
  const [teamsResponse,matchesResponse]=await Promise.all([fetch(`https://www.thebluealliance.com/api/v3/event/${parsed.data.eventKey}/teams/simple`,{headers:{"X-TBA-Auth-Key":key},cache:"no-store"}),fetch(`https://www.thebluealliance.com/api/v3/event/${parsed.data.eventKey}/matches/simple`,{headers:{"X-TBA-Auth-Key":key},cache:"no-store"})]);if(!teamsResponse.ok||!matchesResponse.ok)return{error:"Event saved, but TBA teams or schedule could not be imported."};
  const teams=await teamsResponse.json() as TbaTeam[];const matches=await matchesResponse.json() as TbaMatch[];const {error:teamsError}=await supabase.from("teams").upsert(teams.map(t=>({organization_id:organizationId,team_number:t.team_number,name:t.nickname||`FRC Team ${t.team_number}`})),{onConflict:"organization_id,team_number"});if(teamsError)return{error:"Event saved, but teams could not be imported."};
  const {data:dbTeams}=await supabase.from("teams").select("id,team_number").eq("organization_id",organizationId);const byNumber=new Map((dbTeams??[]).map(t=>[t.team_number,t.id]));const numberFromKey=(teamKey:string)=>Number(teamKey.replace("frc",""));
  const {error:linksError}=await supabase.from("event_teams").upsert(teams.flatMap(t=>{const id=byNumber.get(t.team_number);return id?[{event_id:eventRow.id,team_id:id}]:[]}),{onConflict:"event_id,team_id"});if(linksError)return{error:"Event and teams saved, but event links could not be imported."};
  const mapped=matches.map(m=>({event_id:eventRow.id,match_number:m.match_number,match_type:m.comp_level==="qm"?"qualification":m.comp_level==="pr"?"practice":"playoff",red_teams:m.alliances.red.team_keys.map(numberFromKey).map(n=>byNumber.get(n)).filter((id):id is string=>Boolean(id)),blue_teams:m.alliances.blue.team_keys.map(numberFromKey).map(n=>byNumber.get(n)).filter((id):id is string=>Boolean(id)),scheduled_at:m.time?new Date(m.time*1000).toISOString():null,status:m.actual_time?"played":"scheduled"}));const {error:matchesError}=await supabase.from("matches").upsert(mapped,{onConflict:"event_id,match_type,match_number"});return matchesError?{error:"Teams imported, but matches could not be saved."}:{success:`Imported ${teams.length} teams and ${matches.length} matches from TBA.`};
}catch{return{error:"The import failed. Confirm admin access and try again."};} }
